fix: broken internal links result schema update
adobe/spacecat-audit-worker pull request #460
Opened 2024-11-12 05:39 UTC by nitinja

Issue: https://jira.corp.adobe.com/browse/SITES-25870
Linked PR for reporting: https://github.com/adobe/spacecat-reporting-worker/pull/47

Audit result schema updated to match with broken internal links (as specified below).
```
{
                "url_suggested": "https://www.petplace.com/article/cats/pet-health/cats-and-mating",
                "url_to": "https://example.com/broken-page",
                "title": "Example Page Title",
                "url_from": "https://referrer.com/referring-page",
                "traffic_domain": 50000
}
```
Note:
- `url_suggested` field is not implemented yet.
- `title` is not available from RUM data (checked RUM bundles), so excluded

Please ensure your pull request adheres to the following guidelines:
- [x ] make sure to link the related issues in this description
- [ x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

2024-11-12 09:04 UTC, iuliag requested changes
Could you also include these changes as they are related to the audit worker code?
- https://github.com/adobe/spacecat-reporting-worker/pull/47#discussion_r1836969349: when you store the list in the `auditResult`, it needs to be named `brokenInternalLinks`, not as it is now `internalLinks` (change to add in https://github.com/adobe/spacecat-audit-worker/pull/460/files#diff-d4ce94cf54a5d39f11ed8a64fa377d84c20431e7b250cf86da5515e184fa5fb5R95)
- https://github.com/adobe/spacecat-reporting-worker/pull/47#discussion_r1837012320: `auditResult` (change to add in https://github.com/adobe/spacecat-audit-worker/pull/460/files#diff-d4ce94cf54a5d39f11ed8a64fa377d84c20431e7b250cf86da5515e184fa5fb5R94) should include the `finalUrl` value, the one passed int he options to the RUM query (line https://github.com/adobe/spacecat-audit-worker/pull/460/files#diff-d4ce94cf54a5d39f11ed8a64fa377d84c20431e7b250cf86da5515e184fa5fb5R85).

Apart from these, the PR is good to go 👍🏻

2024-11-12 16:37 UTC, nitinja commented on src/internal-links/handler.js
> +      for (const source of sameDomainSources) {
It's from all sources I think, no way to know exact number of hits from same domain for now - but I will research this and see if it provides such a count from same domain.

2024-11-13 13:48 UTC, iuliag approved these changes

2024-11-13 14:07 UTC, merged

2024-11-13 14:10 UTC, solaris007 commented
:tada: This PR is included in version 1.32.10 :tada:

The release is available on:
- `v1.32.10`
- [GitHub release](https://github.com/adobe/spacecat-audit-worker/releases/tag/v1.32.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: